import type React from "react";
import { useTranslation } from "react-i18next";
import {
  LayoutDashboard, FileText, History, FolderOpen, Bot, Settings, Sun, Moon, Menu,
  Search, Download, Upload, Plus, X, Save, RefreshCw, FilePen, Wrench, Eye, Zap,
  CheckCircle, CircleX, AlertTriangle, Lightbulb, BarChart3, Target, Star, ThumbsUp,
  BookOpen, Bell, User, ChevronRight, Home, Database, Users, Sparkles, Shield,
  Briefcase, LogIn, LogOut, Trash2, AlertCircle, Clock, Activity, Sliders, Layers3,
  ShieldCheck, Check, ArrowRight, ArrowLeft, Mail, Lock, Loader2, Play, FastForward
} from "lucide-react";import type { DocumentItem, HistoryItem } from "../domain/types";

export function ReviewsView({ items, onSelect, onDelete, onNewReview }: { items: HistoryItem[]; onSelect: (id: string) => void; onDelete: (id: string) => void; onNewReview: () => void }) {
  const { t, i18n } = useTranslation();
  return <section className="page-stack"><div className="page-header"><div><div className="page-eyebrow">{t("nav.workspace")}</div><h2>{t("reviews.title")}</h2><p className="page-subtitle">{t("reviews.subtitle")}</p></div><button className="btn-primary" onClick={onNewReview}><Plus size={16} /> {t("reviews.new")}</button></div>{items.length === 0 ? <div className="empty-state"><FileText size={40} /><h2>{t("reviews.empty_title")}</h2><p>{t("reviews.empty_desc")}</p><button className="btn-primary" onClick={onNewReview}><Plus size={16} /> {t("reviews.new")}</button></div> : <div className="reviews-grid">{items.map(item => <article key={item.id} className="review-card"><button className="review-card-main" onClick={() => onSelect(item.id)}><div className="rc-header"><BarChart3 size={20} style={{ color: item.score >= 80 ? "var(--success)" : item.score >= 50 ? "var(--warning)" : "var(--danger)" }} /><div className="rc-info"><strong className="rc-name">{item.filename}</strong><div className="rc-meta"><span className={`badge ${item.status}`}>{item.status}</span><span>{item.profile_id}</span><span>{item.created_at ? new Date(item.created_at).toLocaleDateString(i18n.language) : ""}</span></div></div><div className="rc-score">{item.score}</div></div>{item.summary && <p className="rc-summary">{item.summary}</p>}</button><button className="btn-icon danger review-delete" aria-label={t("common.delete")} onClick={() => onDelete(item.id)}><Trash2 size={14} /></button></article>)}</div>}</section>;
}

export function HistoryView({ items, onSelect, onDelete }: { items: HistoryItem[]; onSelect: (id: string) => void; onDelete: (id: string) => void }) {
  const { t, i18n } = useTranslation();
  return <section className="page-stack"><div className="page-header"><div><div className="page-eyebrow">{t("nav.workspace")}</div><h2>{t("history.title")}</h2><p className="page-subtitle">{t("history.subtitle")}</p></div></div>{items.length === 0 ? <div className="empty-state"><History size={40} /><h2>{t("history.empty_title")}</h2><p>{t("history.empty_desc")}</p></div> : <div className="history-list">{items.map(item => <article key={item.id} className="history-card"><button className="history-card-main" onClick={() => onSelect(item.id)}><div className="hc-left"><BarChart3 size={24} /></div><div className="hc-body"><div className="hc-title"><strong>{item.filename}</strong><span className={`badge ${item.status}`}>{item.status}</span></div><div className="hc-meta"><span>{t("common.score")}: {item.score}</span><span>{t("common.profile")}: {item.profile_id}</span><span>{item.created_at ? new Date(item.created_at).toLocaleDateString(i18n.language) : ""}</span></div>{item.summary && <div className="hc-summary">{item.summary}</div>}</div><Eye size={16} /></button><button className="btn-icon danger history-delete" aria-label={t("common.delete")} onClick={() => onDelete(item.id)}><Trash2 size={14} /></button></article>)}</div>}</section>;
}

export function DocumentsView({ documents, onUpload, onDelete, onReview, uploadInputRef, isUploading }: { documents: DocumentItem[]; onUpload: (file: File) => void; onDelete: (id: string) => void; onReview: (id: string) => void; uploadInputRef: React.RefObject<HTMLInputElement | null>; isUploading?: boolean; }) {
  const { t, i18n } = useTranslation();
  const handleUpload = (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (file) onUpload(file); event.target.value = ""; };
  return <section className="page-stack"><div className="page-header"><div><div className="page-eyebrow">{t("nav.workspace")}</div><h2>{t("documents.title")}</h2><p className="page-subtitle">{t("documents.subtitle")}</p></div><button className="btn-primary" onClick={() => uploadInputRef.current?.click()} disabled={isUploading}>{isUploading ? <Loader2 size={16} className="spin" /> : <Upload size={16} />} {isUploading ? t("documents.uploading") : t("documents.upload")}</button><input ref={uploadInputRef} type="file" accept=".txt,.md,.docx,.pdf" hidden onChange={handleUpload} /></div>{documents.length === 0 ? <div className="empty-state"><FolderOpen size={40} /><h2>{t("documents.empty_title")}</h2><p>{t("documents.empty_desc")}</p><button className="btn-primary" onClick={() => uploadInputRef.current?.click()}><Upload size={15} /> {t("documents.upload")}</button></div> : <div className="documents-grid">{documents.map(doc => <article key={doc.id} className="document-card"><div className="doc-card-icon"><FileText size={24} /></div><div className="doc-card-info"><strong>{doc.name}</strong><span>{new Date(doc.uploaded_at).toLocaleDateString(i18n.language)}</span></div><div className="document-actions"><button className="btn-sm outline" onClick={() => onReview(doc.id)}><Play size={13} /> {t("documents.review")}</button><button className="btn-icon danger" aria-label={t("common.delete")} onClick={() => onDelete(doc.id)}><Trash2 size={14} /></button></div></article>)}</div>}</section>;
}

