from __future__ import annotations

from ..models import Issue


_TRANSLATIONS = {
    "en": {
        "title": "ReviewMind Quality Report", "profile": "Profile", "overall": "Overall Score", "status": "Status",
        "overview": "Document Overview", "metric": "Metric", "value": "Value", "breakdown": "Score Breakdown",
        "category": "Category", "score": "Score", "grade": "Grade", "excellent": "Excellent", "good": "Good",
        "needs_work": "Needs Work", "summary": "Issue Summary", "severity": "Severity", "count": "Count",
        "autofixable": "Auto-Fixable", "autofix_sentence": "{count} issue(s) can be automatically fixed.",
        "issues": "Issues", "no_issues": "No issues were detected. The document meets all quality standards.",
        "rule": "Rule", "evidence": "Evidence", "recommendation": "Recommendation", "auto_fixable": "Auto-fixable",
        "generated": "Generated by ReviewMind — AI-powered Document Review Platform",
        "draft": "Draft", "review_needed": "Review Needed", "almost_ready": "Almost Ready", "ready": "Ready to Submit",
        "critical": "Critical", "high": "High", "medium": "Medium", "low": "Low",
        "pages": "Pages", "words": "Words", "paragraphs": "Paragraphs", "headings": "Headings",
        "tables": "Tables", "figures": "Figures", "references": "References",
    },
    "vi": {
        "title": "Báo cáo Chất lượng ReviewMind", "profile": "Hồ sơ", "overall": "Điểm tổng thể", "status": "Trạng thái",
        "overview": "Tổng quan tài liệu", "metric": "Chỉ số", "value": "Giá trị", "breakdown": "Phân tích điểm",
        "category": "Nhóm", "score": "Điểm", "grade": "Xếp loại", "excellent": "Xuất sắc", "good": "Tốt",
        "needs_work": "Cần cải thiện", "summary": "Tóm tắt vấn đề", "severity": "Mức độ", "count": "Số lượng",
        "autofixable": "Có thể tự sửa", "autofix_sentence": "Có thể tự động sửa {count} vấn đề.",
        "issues": "Chi tiết vấn đề", "no_issues": "Không phát hiện vấn đề. Tài liệu đáp ứng các tiêu chuẩn chất lượng.",
        "rule": "Quy tắc", "evidence": "Bằng chứng", "recommendation": "Khuyến nghị", "auto_fixable": "Có thể tự sửa",
        "generated": "Tạo bởi ReviewMind — Nền tảng đánh giá tài liệu hỗ trợ bởi AI",
        "draft": "Bản nháp", "review_needed": "Cần xem lại", "almost_ready": "Gần sẵn sàng", "ready": "Sẵn sàng gửi",
        "critical": "Nghiêm trọng", "high": "Cao", "medium": "Trung bình", "low": "Thấp",
        "pages": "Trang", "words": "Từ", "paragraphs": "Đoạn", "headings": "Tiêu đề",
        "tables": "Bảng", "figures": "Hình", "references": "Tài liệu tham khảo",
    },
}


def render_markdown(
    profile_id: str,
    score: int,
    issues: list[Issue],
    category_scores: dict | None = None,
    doc_stats: dict | None = None,
    readiness_level: str = "",
    language: str = "en",
) -> str:
    """Render a localized, structured Markdown quality report."""
    tr = _TRANSLATIONS.get(language, _TRANSLATIONS["en"])
    readiness_emoji = {"draft": "🟥", "review_needed": "🟧", "almost_ready": "🟨", "ready": "🟩"}
    severity_icons = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🔵"}

    lines: list[str] = [
        f"# {tr['title']}", "", f"**{tr['profile']}:** {profile_id}", f"**{tr['overall']}:** {score}/100",
    ]
    if readiness_level:
        lines.append(f"**{tr['status']}:** {readiness_emoji.get(readiness_level, '')} {tr.get(readiness_level, readiness_level)}".rstrip())
    lines.append("")

    if doc_stats:
        lines += [f"## {tr['overview']}", "", f"| {tr['metric']} | {tr['value']} |", "|---|---:|"]
        for key in ("pages", "words", "paragraphs", "headings", "tables", "figures", "references"):
            if key in doc_stats:
                lines.append(f"| {tr[key]} | {doc_stats[key]} |")
        lines.append("")

    if category_scores:
        lines += [f"## {tr['breakdown']}", "", f"| {tr['category']} | {tr['score']} | {tr['grade']} |", "|---|---:|---|"]
        for category, category_score in category_scores.items():
            grade = tr["excellent"] if category_score >= 80 else tr["good"] if category_score >= 65 else tr["needs_work"]
            grade_icon = "🟢" if category_score >= 80 else "🟡" if category_score >= 65 else "🔴"
            lines.append(f"| {category.title()} | {category_score}/100 | {grade_icon} {grade} |")
        lines.append("")

    by_severity: dict[str, int] = {}
    for issue in issues:
        severity = issue.severity.value if hasattr(issue.severity, "value") else str(issue.severity)
        by_severity[severity] = by_severity.get(severity, 0) + 1
    auto_fixable = sum(1 for issue in issues if issue.autofix_allowed)
    lines += [f"## {tr['summary']}", "", f"| {tr['severity']} | {tr['count']} |", "|---|---:|"]
    for severity in ("critical", "high", "medium", "low"):
        if by_severity.get(severity):
            lines.append(f"| {severity_icons[severity]} {tr[severity]} | {by_severity[severity]} |")
    lines += ["", f"**{tr['autofixable']}:** {tr['autofix_sentence'].format(count=auto_fixable)}", "", f"## {tr['issues']}", ""]

    if not issues:
        lines.append(f"✅ {tr['no_issues']}")
    else:
        by_category: dict[str, list[Issue]] = {}
        for issue in issues:
            by_category.setdefault(issue.category, []).append(issue)
        for category, category_issues in sorted(by_category.items()):
            lines += [f"### {category.title()}", ""]
            for issue in category_issues:
                severity = issue.severity.value if hasattr(issue.severity, "value") else str(issue.severity)
                fix_badge = f"🔧 {tr['auto_fixable']}" if issue.autofix_allowed else ""
                lines += [
                    f"#### {severity_icons.get(severity, '')} {issue.message} {fix_badge}".rstrip(),
                    f"- **{tr['rule']}:** `{issue.rule_id}`",
                    f"- **{tr['severity']}:** {tr.get(severity, severity.title())}",
                ]
                if issue.evidence.excerpt:
                    lines.append(f"- **{tr['evidence']}:** _{issue.evidence.excerpt[:200]}_")
                if issue.recommendation:
                    lines.append(f"- **{tr['recommendation']}:** {issue.recommendation}")
                lines.append("")

    lines += ["---", f"_{tr['generated']}_"]
    return "\n".join(lines)